/**
 * Internal error codes.
 */
export const ERROR_CODES = {
  USER_ALREADY_EXIST: "USER_ALREADY_EXIST",
  CREATE_USER_FAILED: "CREATE_USER_FAILED",

  USER_NOT_FOUND: "USER_NOT_FOUND",
  INCORRECT_PASSWORD: "INCORRECT_PASSWORD",
  UPDATE_PASSWORD_FAILED: "UPDATE_PASSWORD_FAILED",

  TOKEN_CREATION_FAILED: "TOKEN_CREATION_FAILED",
  TOKENS_ALREADY_EXIST: "TOKENS_ALREADY_EXIST",
  NO_TOKENS_FOUND: "NO_TOKENS_FOUND",
  NO_VALID_TOKENS_FOUND: "NO_VALID_TOKENS_FOUND",
  INVALID_TOKEN: "INVALID_TOKEN",
  DELETE_TOKEN_FAILED: "DELETE_TOKEN_FAILED",
};