CREATE DATABASE IF NOT EXISTS chat_app;

USE chat_app;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(256) UNIQUE NOT NULL,
    name VARCHAR(64) UNIQUE NOT NULL,
    password CHAR(60) NOT NULL, -- bcrypt hash which is 60 bytes or 60 chars
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rooms (
    id BIGINT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(64) CHARACTER SET UTF8MB4,
    password VARCHAR(64) CHARACTER SET UTF8MB4,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS room_members (
    room_id BIGINT(20) UNSIGNED NOT NULL,
    user_id BIGINT(20) UNSIGNED NOT NULL,
    PRIMARY KEY (room_id, user_id),
    FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    room_id BIGINT(20) UNSIGNED NOT NULL,
    user_id BIGINT(20) UNSIGNED,
    content VARCHAR(500) CHARACTER SET UTF8MB4 NOT NULL,
    FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL,
    created TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS reset_tokens (
    token BINARY(32) UNIQUE NOT NULL, -- token hash using SHA256 which is 32 bytes
    user_id BIGINT(20) UNSIGNED PRIMARY KEY,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    created TIMESTAMP NOT NULL,
    expires TIMESTAMP NOT NULL
);

CREATE EVENT IF NOT EXISTS cleanup_reset_tokens
    ON SCHEDULE EVERY 30 MINUTE
    COMMENT 'Delete expired reset tokens'
    DO
        DELETE FROM reset_tokens WHERE expires < CURRENT_TIMESTAMP;