CREATE DATABASE IF NOT EXISTS chat_app;

USE chat_app;

CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(50) UNIQUE NOT NULL,
    password CHAR(60) NOT NULL, -- bcrypt hash
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rooms (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(64) CHARACTER SET UTF8MB4,
    password VARCHAR(64) CHARACTER SET UTF8MB4
);

CREATE TABLE IF NOT EXISTS room_members (
    room_id INT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    PRIMARY KEY (room_id, user_id),
    FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS messages (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    room_id INT UNSIGNED NOT NULL,
    user_id INT UNSIGNED,
    content VARCHAR(500) CHARACTER SET UTF8MB4 NOT NULL,
    FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL,
    created TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS reset_tokens (
    token BINARY(32) UNIQUE NOT NULL, -- token hash using SHA256
    user_id INT UNSIGNED PRIMARY KEY,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    created TIMESTAMP NOT NULL,
    expires TIMESTAMP NOT NULL
);

CREATE EVENT IF NOT EXISTS cleanup_reset_tokens
    ON SCHEDULE EVERY 30 MINUTE
    COMMENT 'Delete expired reset tokens'
    DO
        DELETE FROM reset_tokens WHERE expires < CURRENT_TIMESTAMP;