/** 
 * Internal error codes
 */
export const ERROR_CODES = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  USER_NOT_IN_ROOM: 'USER_NOT_IN_ROOM',
  INSUFFICIENT_PRIVILEGE: 'INSUFFICIENT_PRIVILEGE',
};